title: Biologie Numérique à Bordeaux
theme: jekyll-theme-tactile
description: Les rencontres entre bioinfos bordelais·es

nav:
  - Home: 'index.md'
  - Séminaires: 
    - Titres:
      - 'index.md'
      - '2024.md'
      - '2023.md'
      - '2022.md'
      - '2021.md'
      - '2020.md'
    - Résumés:
      - resumes.md
  - Autres événements: 'about.md'

